/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sparkw3;


import spark.Spark;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Spark.get("/users/:id/welcome", (req, res) -> {return "Happy Birthday " + req.params("id");});

    }
}
